$ErrorActionPreference = 'Continue'

$root = Split-Path -Parent $PSScriptRoot
$dataPath = Join-Path $root 'final-fantasy-releases.js'
$assetDirectory = Join-Path $root 'assets\final-fantasy-covers'
$mapPath = Join-Path $root 'final-fantasy-covers.js'
$headers = @{ 'User-Agent' = 'GameArchiveLocal/1.0 (personal archival project)' }

New-Item -ItemType Directory -Path $assetDirectory -Force | Out-Null
$source = Get-Content -Raw -LiteralPath $dataPath
$matches = [regex]::Matches($source, '\{ id: "(?<id>[^"]+)", date: "[^"]+", category: "[^"]+", name: "(?<name>[^"]+)"')
$covers = [ordered]@{}
$missing = [System.Collections.Generic.List[string]]::new()
$releases = foreach ($match in $matches) {
  [pscustomobject]@{ Id = $match.Groups['id'].Value; Name = $match.Groups['name'].Value }
}
$byTitle = @{}
foreach ($release in $releases) { $byTitle[$release.Name.ToLowerInvariant()] = $release }

for ($index = 0; $index -lt $releases.Count; $index += 20) {
  $batch = @($releases | Select-Object -Skip $index -First 20)
  $titles = [uri]::EscapeDataString(($batch.Name -join '|'))
  $queryUrl = "https://en.wikipedia.org/w/api.php?action=query&format=json&redirects=1&prop=pageimages&pithumbsize=700&pilicense=any&titles=$titles"

  try {
    $query = Invoke-RestMethod -Uri $queryUrl -Headers $headers -TimeoutSec 45
  } catch {
    foreach ($release in $batch) { $missing.Add($release.Id) }
    Start-Sleep -Seconds 4
    continue
  }

  $resolvedTitles = @{}
  foreach ($redirect in @($query.query.redirects)) {
    $sourceRelease = $byTitle[$redirect.from.ToLowerInvariant()]
    if ($sourceRelease) { $resolvedTitles[$redirect.to.ToLowerInvariant()] = $sourceRelease }
  }

  foreach ($page in $query.query.pages.PSObject.Properties.Value) {
    $release = $byTitle[$page.title.ToLowerInvariant()]
    if (-not $release) { $release = $resolvedTitles[$page.title.ToLowerInvariant()] }
    $imageUrl = $page.original.source
    if (-not $imageUrl) { $imageUrl = $page.thumbnail.source }
    if (-not $release -or -not $imageUrl) { continue }

    try {
      $extension = [IO.Path]::GetExtension(([uri]$imageUrl).AbsolutePath).ToLowerInvariant()
      if ($extension -notin '.jpg', '.jpeg', '.png', '.webp') { $extension = '.jpg' }
      if ($extension -eq '.jpeg') { $extension = '.jpg' }
      $filename = "$($release.Id)$extension"
      $target = Join-Path $assetDirectory $filename
      if (-not (Test-Path -LiteralPath $target)) {
        Invoke-WebRequest -Uri $imageUrl -Headers $headers -OutFile $target -TimeoutSec 45
        Start-Sleep -Milliseconds 1400
      }
      $covers[$release.Id] = @(@($filename, $release.Name))
    } catch {
      $missing.Add($release.Id)
    }
  }
  Start-Sleep -Seconds 3
}

foreach ($release in $releases) {
  if (-not $covers.Contains($release.Id) -and -not $missing.Contains($release.Id)) {
    $missing.Add($release.Id)
  }
}

$json = $covers | ConvertTo-Json -Depth 4
"// Generated by scripts/fetch-final-fantasy-covers.ps1.`nwindow.FINAL_FANTASY_RELEASE_COVERS = $json;`n" | Set-Content -LiteralPath $mapPath -Encoding utf8
[pscustomobject]@{ Downloaded = $covers.Count; Missing = $missing } | ConvertTo-Json -Depth 3
