$ErrorActionPreference = 'Continue'

$root = Split-Path -Parent $PSScriptRoot
$dataPath = Join-Path $root 'final-fantasy-releases.js'
$assetDirectory = Join-Path $root 'assets\final-fantasy-logos'
$mapPath = Join-Path $root 'final-fantasy-logos.js'
$headers = @{ 'User-Agent' = 'GameArchiveLocal/1.0 (personal archival project)' }
$api = 'https://finalfantasywiki.com/w/api.php'

Add-Type -AssemblyName System.Drawing

New-Item -ItemType Directory -Path $assetDirectory -Force | Out-Null
$source = Get-Content -Raw -LiteralPath $dataPath
$matches = [regex]::Matches($source, '\{ id: "(?<id>[^"]+)"[\s\S]*?name: "(?<name>[^"]+)"')
$logos = [ordered]@{}
if (Test-Path -LiteralPath $mapPath) {
  $existingSource = Get-Content -Raw -LiteralPath $mapPath
  $existingJson = $existingSource -replace '(?s)^.*?=\s*', '' -replace ';\s*$', ''
  try {
    $existing = $existingJson | ConvertFrom-Json
    foreach ($property in $existing.PSObject.Properties) {
      $logos[$property.Name] = @($property.Value)
    }
  } catch {
    # A previous interrupted run may leave an incomplete generated map.
    $logos.Clear()
  }
}

# These entries use an alternate canonical page title on Final Fantasy Wiki.
$pageTitleOverrides = @{
  'ff11' = 'Final Fantasy XI'
  'ff-dimensions' = 'Final Fantasy Legends: Warriors of Light and Darkness'
  'ff-dimensions-2' = 'Final Fantasy Legends: The Space-Time Crystal'
}

$releases = foreach ($match in $matches) {
  $id = $match.Groups['id'].Value
  [pscustomobject]@{
    Id = $id
    Name = $match.Groups['name'].Value
    LookupTitle = if ($pageTitleOverrides.ContainsKey($id)) { $pageTitleOverrides[$id] } else { $match.Groups['name'].Value }
  }
}

$downloaded = 0
$missing = [System.Collections.Generic.List[string]]::new()
foreach ($release in $releases) {
  if ($logos.Contains($release.Id)) { continue }

  try {
    # Final Fantasy Wiki archives most title logos in Gallery: pages. Only use
    # the game page as a fallback when a dedicated gallery has no logo file.
    $logoFile = $null
    foreach ($pageTitle in @("Gallery:$($release.LookupTitle)", $release.LookupTitle)) {
      $pageUrl = "${api}?action=query&format=json&prop=images&imlimit=500&titles=$([uri]::EscapeDataString($pageTitle))"
      $pageResult = Invoke-RestMethod -Uri $pageUrl -Headers $headers -TimeoutSec 30
      $page = $pageResult.query.pages.PSObject.Properties.Value | Select-Object -First 1
      $logoFile = $page.images |
        Where-Object { $_.title -match '(?i)logo|wordmark' -and $_.title -notmatch '(?i)wikipedia' } |
        Select-Object -First 1
      if ($logoFile) { break }
      Start-Sleep -Seconds 2
    }
    if (-not $logoFile) { $missing.Add($release.Id); Start-Sleep -Seconds 3; continue }

    $fileUrl = "${api}?action=query&format=json&prop=imageinfo&iiprop=url&titles=$([uri]::EscapeDataString($logoFile.title))"
    $fileResult = Invoke-RestMethod -Uri $fileUrl -Headers $headers -TimeoutSec 30
    $filePage = $fileResult.query.pages.PSObject.Properties.Value | Select-Object -First 1
    $imageUrl = $filePage.imageinfo[0].url
    if (-not $imageUrl) { $missing.Add($release.Id); Start-Sleep -Seconds 3; continue }

    $extension = [IO.Path]::GetExtension(([uri]$imageUrl).AbsolutePath).ToLowerInvariant()
    if ($extension -notin '.jpg', '.jpeg', '.png', '.webp') { $extension = '.png' }
    if ($extension -eq '.jpeg') { $extension = '.jpg' }
    $filename = "$($release.Id)-logo$extension"
    $target = Join-Path $assetDirectory $filename
    Invoke-WebRequest -Uri $imageUrl -Headers $headers -OutFile $target -TimeoutSec 45
    $image = [System.Drawing.Image]::FromFile((Resolve-Path $target))
    $isHorizontal = $image.Width -ge $image.Height
    $image.Dispose()
    if (-not $isHorizontal) {
      Remove-Item -LiteralPath $target -Force
      $missing.Add($release.Id)
      Start-Sleep -Seconds 3
      continue
    }
    $logos[$release.Id] = @($filename, $release.Name)
    $downloaded++
  } catch {
    $missing.Add($release.Id)
  }

  # Avoid triggering the community wiki's image and API rate limits.
  Start-Sleep -Seconds 3
}

$json = $logos | ConvertTo-Json -Depth 4
"// Generated by scripts/fetch-final-fantasy-logos.ps1.`nwindow.FINAL_FANTASY_RELEASE_LOGOS = $json;`n" | Set-Content -LiteralPath $mapPath -Encoding utf8
[pscustomobject]@{ Downloaded = $downloaded; Total = $logos.Count; Missing = $missing } | ConvertTo-Json -Depth 3
